### ISSUE TITLE
aead_mac can't handle large large cipher text

### ISSUE THREAD

**Issue by CharlieEriksen** [devi/chacha20poly1305#2]
If you try to generate a mac with aead_mac for a ciphertext(For instanced, a string of 341.000 characters) that is any kind of big(Not really that big), then it will throw a max call stack size exception due to the Array.apply call using the ciphertext as an argument, which puts the full ciphertext on the stack, which is not good.
Consider replacing:

```
  m = m.concat(Array.apply([], ciphertext));
```

With this:
```
    for(var q = 0; q < ciphertext.length; q++){
        m.push(ciphertext[q]);
    }
```

From my quick testing, it doesn't seem to break anything, and it can handle at least a medium sized input(Like 341k characters).

**Comment by devi** [comment]
Thank you for spotting this.
